name: Daily Hit Score Refresh

on:
  schedule:
    - cron: "0 13 * * *"  # 8:00 AM CDT = 13:00 UTC
  workflow_dispatch:      # Allows you to run manually

jobs:
  refresh:
    runs-on: ubuntu-latest

    steps:
      - name: Hit the rankings endpoint
        run: |
          curl -X GET https://hit-score-api.onrender.com/rankings
